services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstuio-app-test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bookstudio_test
      - IS_DOCKER=true
    depends_on:
      - db
    networks:
      - bookstuio-test-network
    command: ["npm", "test"]

  db:
    image: postgres:15-alpine
    container_name: bookstuio-db-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstudio_test
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - bookstuio-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bookstudio_test -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  bookstuio-test-network:
    driver: bridge