// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bookstud-restyle/BroadcastPro.tsx": () => import("../components/mockups/bookstud-restyle/BroadcastPro.tsx"),
  "./components/mockups/bookstud-restyle/ModernMinimal.tsx": () => import("../components/mockups/bookstud-restyle/ModernMinimal.tsx"),
  "./components/mockups/bookstud-restyle/WarmEditorial.tsx": () => import("../components/mockups/bookstud-restyle/WarmEditorial.tsx"),
  "./components/mockups/bookstud-calendar/BroadcastPro.tsx": () => import("../components/mockups/bookstud-calendar/BroadcastPro.tsx"),
  "./components/mockups/bookstud-calendar/Current.tsx": () => import("../components/mockups/bookstud-calendar/Current.tsx"),
  "./components/mockups/bookstud-calendar/ModernMinimal.tsx": () => import("../components/mockups/bookstud-calendar/ModernMinimal.tsx"),
  "./components/mockups/bookstud-calendar/WarmEditorial.tsx": () => import("../components/mockups/bookstud-calendar/WarmEditorial.tsx")
};
